Feat: Add Login Page HTML
mbta/sso-static pull request #1
Opened 2021-10-28 21:24 UTC by krisrjohnson21

Login page for IntegSoft and stylesheet ready for initial review.

Annotated designs here (slide 2): https://mbta.sharepoint.com/:p:/s/CTD/EVcdHrlzby9KhYGCqGsmEj0BocFlI-JB-CsOJOJkcNGnhw?email=krisjohnson%40MBTA.com&e=4%3Aif8p3Z&wdLOR=cD59EB8E3-0DA7-774D-BFA1-F7C22879B7EE

2021-10-29 20:38 UTC, thecristen requested changes
Assorted comments. I noticed there's some differences between the mockup and this implementation (h1, label font-weights are most noticeable); is the intention to discard the mockup in favor of the MBTA.com style instead? Is whoever designed this also going to review this, or did you want to rely on my review for design review as well? Just curious.

2021-10-29 20:38 UTC, thecristen commented on login.html
> +<html>
```suggestion
<html lang="en">
```

(It's an accessibility thing)

2021-10-29 20:38 UTC, thecristen commented on login.html
> +                    <label class="form-input-label" for="form-input-email">Username or email</label>
The label for attribute should point to the input id attribute rather than the name.

2021-10-29 20:38 UTC, thecristen commented on login.html
> +                    <label class="form-input-label" for="form-input-password">Password</label>
The label for attribute should point to the input id attribute rather than the name.

2021-10-29 20:38 UTC, thecristen commented on login.html
> +                <button id="sign-in">Sign In</button>
This form can be wrapped in a `<form>` element and this button become a submit form action e.g `<input type="submit" value="Sign In">`, that way clicking the button can send the form to the backend and take the user to another page...

2021-10-29 20:38 UTC, thecristen commented on login.html
> +                <h1>Sign In To Your Account</h1>
I notice that the `<h1>` styling aligns with MBTA.com's, but the styling in the mockup is pretty different (smaller, lighter font weight) - should that be reconciled?

2021-10-29 20:38 UTC, thecristen commented on assets/stylesheet.css
> +    font-family: Inter UI;
Because Inter UI is not a default font, it has to manually be added to the stylesheet to enable it for users who don't happen to have that font installed. See the Inter font family's usage section for suggested ways to do this: https://rsms.me/inter/#usage

2021-10-29 20:38 UTC, thecristen commented on assets/stylesheet.css
> +    font-family: Helvetica Neue;
There should be a default font-size applied here.

2021-10-29 20:38 UTC, thecristen commented on login.html
> +                    type="text" />
```suggestion
                    type="password" />
```

2021-10-29 20:38 UTC, thecristen commented on login.html
> +                    type="text" />
```suggestion
                    type="email" />
```

2021-10-29 20:38 UTC, thecristen commented on assets/stylesheet.css
> +    font-family: Helvetica Neue;
Also, this should be the Inter font, and Helvetica used only for headings.

2021-10-29 20:38 UTC, thecristen commented on assets/stylesheet.css
> +    font-size: 14px;
```suggestion
```

I think you can remove this and let it inherit the size.

2021-10-29 20:38 UTC, thecristen commented on assets/stylesheet.css
> +    height: 48px;
This height probably doesn't need to be hardcoded here.

2021-10-29 20:38 UTC, thecristen commented on assets/stylesheet.css
> +    border-color: #F2F3F5;
```suggestion
    border: 1px solid #F2F3F5;
```

2021-11-01 19:00 UTC, krisrjohnson21 commented
Thanks @thecristen! I checked the discrepancy with Yinka and he advised that I should rely on ZeroHeight and discard the mockup styling. I'll ask him to have a look at this from a design perspective

2021-11-01 20:04 UTC, krisrjohnson21 commented on login.html
> +                <h1>Sign In To Your Account</h1>
Will double-check this with Yinka 👍

2021-11-01 20:07 UTC, krisrjohnson21 commented on assets/stylesheet.css
> +    font-size: 14px;
Looking closer at ZeroHeight, this should've been dynamic. Made that update in the forthcoming commit

2021-11-02 17:44 UTC, thecristen reviewed
<img width="401" alt="image" src="https://user-images.githubusercontent.com/2136286/139917876-4a68bbf5-a527-4df3-9fe7-cf314b131173.png">

Looking much better, but the scaling on mobile isn't so good. I'm not sure if that's a priority for you at this stage?

2021-11-02 20:11 UTC, krisrjohnson21 commented
I checked with Yinka on this and mobile scaling should be included. I used layouts as described by ZeroHeight. It looks like I can make some improvements to the Sign In button, any other spots to target?

2021-11-02 20:47 UTC, thecristen requested changes
I just pushed up a change that should take care of the type sizes/line heights with less CSS.

More adjustments -
* The padding/margin around the `.page-content` and the `.container`. I think it looks ok in the larger screens, but is too much for smaller screens.  
* Nice to have: button width should still match the input width on smaller screens
* The Forgot Password? link sticks out on the right - it should align with the inputs and the button.

2021-11-02 21:54 UTC, krisrjohnson21 commented
Thank you for these CSS changes, they're really helpful and a good learning experience! I made a couple of changes to address the remaining fixes. It tightened up the large screen view a bit, is this reasonable? The mobile view looks a million times better, however.

2021-11-03 14:19 UTC, thecristen approved these changes
Looks good!

2021-11-03 14:31 UTC, merged